### ISSUE TITLE
Do not load dispatcher when only xsk program is active

### ISSUE THREAD

**Issue by magnus-karlsson** [xdp-project/xdp-tools#103]
The XDP dispatcher has a significant performance impact (up to 11% decrease) on the performance of an AF_XDP socket. One way to get around this is to not load the dispatcher when the default xsk program is the only one active. The dispatcher is not needed in this case.

Toke suggested that we add some special handling of the xsk program and just load it when there is no other XDP program there. If more programs are added, we simply add the dispatcher and in that case the performance drop should be justified, since you are getting added functionality. The question now is: why do we not do this for any program, i.e. only load the dispatcher only if there are two or more XDP programs that want to share an interface? The only reason I can come up with is that it is much faster to add or remove a program if the dispatcher is already there. Adding the dispatcher plus two programs might result in dropped packets due to this latency, but I do not know. Other reasons?

Plan from Toke:

- When attaching XSK program, if nothing is attached already, just
  attach it directly to the interface.

- When attaching XSK program and another program is already installed,
  do the regular thing and attach it as a secondary program with a
  dispatcher.

- When attaching *another* program and an XSK program is already
  attached, generate a new dispatcher with a new copy of the XSK program
  as one of the sub-programs, but reusing the map from the program
  already attached to the interface; then replace the existing program
  with that dispatcher.

**Comment by tohojo** [comment]
First off, @shoracek had an idea that may obviate the need for that whole dance: Simply attach the freplace program to the main function of the dispatcher if there's only a single component program; that way there won't be an additional function call, and I'm hoping the overhead will (mostly? entirely?) go away then. Stepan, do you want to take a crack at implementing this? Otherwise I'll take a look once I've cleared a few other things off my plate...

But to explain further, the reason we can't just attach other programs like regular XDP programs and then install the dispatcher once a second program shows up, is that we can't change the program type once it's loaded. And when we're attaching a program with freplace it needs to be loaded with `BPF_PROG_TYPE_EXT` as its program type at load time.

With the AF_XDP program we can just load another copy of the program with the right type, because we have the object file handy as part of the library. But for user-loaded XDP programs we can't, unless we cache the object files somewhere, and that I'd rather not do...

**Comment by shoracek** [comment]
Sure thing, I'll try to figure something out.

**Comment by tohojo** [comment]
Štěpán Horáček ***@***.***> writes:

> Sure thing, I'll try to figure something out.

Great, thanks! :)

Should be fairly straight-forward: I think we can keep the pinning and
everything in place and just change the freplace attach target when
there's only one program. But I may be missing something, so please
double check that it doesn't break (e.g.) reporting of attached programs
or something like that...
