### ISSUE TITLE
XDP Filter

### ISSUE THREAD

**Issue by gul-e-hasnain** [xdp-project/xdp-tools#268]
I want to print the source and destination IP capture by eBPF in terminal. How can this be solved?

**Comment by tohojo** [comment]
This repository is used to develop the `xdp-tools` utilities and the `libxdp` library. This means that the issue tracker is for tracking bugs in these, it's not a general support forum for BPF and XDP programming.

Since your question is not related to `xdp-tools` I'm closing this issue. Please try one of these resources instead for general BPF help:

- The BPF Slack channel: https://ebpf.io/slack/
- Stack overflow: https://stackoverflow.com/questions/tagged/ebpf+or+bpf+or+xdp-bpf+or+xdp-ebpf+or+bcc-bpf+or+libbpf+or+bpftrace
- Reddit /r/eBPF: https://www.reddit.com/r/eBPF/
