### ISSUE TITLE
Help， libbpf can't create map in /sys/fs/lib/bpf

### ISSUE THREAD

**Issue by xjj210130** [xdp-project/xdp-tools#337]
hi all:
My env is centos 7. core is 5.15.46 (build by myself) gcc 11.2.1 clang 14.0.6 llvm 14.0.6 bpftool is v5.15.46

I do as following:
1: git clone https://github.com/xdp-project/bpf-examples.git
2: cd bpf-examples/lib and build libbpf libxdp
3: bpf-examples/AF_XDP-example and modify the code as following:
xdpsock._kern.c only do this

SEC("xdp_sock") int xdp_sock_prog(struct xdp_md *ctx)
{
rr = (rr + 1) & (MAX_SOCKS - 1);
bpf_printk("hell--------------test-----\n");
bpf_trace_printk("hell----------------11-%d--",12);
void *data = (void *)(long)ctx->data;
void *data_end = (void *)(long)ctx->data_end;
if (NULL == data || NULL == data_end)
{
bpf_printk(" data is null, packet is wrong \n");
return XDP_DROP;

}
return bpf_redirect_map(&xsks_map, rr, XDP_DROP);
}

4: make
5: run ./xdpsock -i eno2 -q 5 -r -M

There is other wrong message:
libbpf: prog 'xdp_dispatcher': failed to load: -22
libbpf: failed to load object '/usr/local/lib/bpf/xdp-dispatcher.o'
libxdp: Failed to load dispatcher: Invalid argument
libxdp: Falling back to loading single prog without dispatcher

libbpf: prog 'xdp_dispatcher': failed to load: -22
libbpf: failed to load object '/usr/local/lib/bpf/xdp-dispatcher.o'
libxdp: Failed to load dispatcher: Invalid argument
libxdp: Falling back to loading single prog without dispatcher

load_xdp_program fisnish, 5, 1

It looks like attach the xdp program on network. However , it doesn't work.  There is nothing  under the folder /sys/fs/lib/bpf.

Could you help me how to solve the problem.
Thanks.

**Comment by tohojo** [comment]
Why would you expect there to be anything in bpffs? That example doesn't
use map pinning at all...

**Comment by xjj210130** [comment]
emm，  I  run cmd : cat /sys/kernel/debug/tracing/trace_pipe
There is nothing appear. It should be "hell--------------test-". So i think the  function xdp_sock_prog don't work.  It looks like don't attach the xdp program on network.

**Comment by tohojo** [comment]
This repository is used to develop the `xdp-tools` utilities and the `libxdp` library. This means that the issue tracker is for tracking bugs in these, it's not a general support forum for BPF and XDP programming.

Since your question is not related to `xdp-tools` I'm closing this issue. Please try one of these resources instead for general BPF help:

- The BPF Slack channel: https://ebpf.io/slack/
- Stack overflow: https://stackoverflow.com/questions/tagged/ebpf+or+bpf+or+xdp-bpf+or+xdp-ebpf+or+bcc-bpf+or+libbpf+or+bpftrace
- Reddit /r/eBPF: https://www.reddit.com/r/eBPF/
